driver:
  name: vagrant
  require_chef_omnibus: '11.14'

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-6.8
  - name: centos-7.3
  - name: debian-7.11
  - name: debian-8.6
  - name: freebsd-10.3
  - name: freebsd-11.0
  - name: fedora-25
  - name: opensuse-leap-42.2
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: windows-2008r2
    driver:
      box: chef/windows-server-2008r2-standard # private box in Chef's Atlas account
  - name: windows-2012r2
    driver:
      box: chef/windows-server-2012r2-standard # private box in Chef's Atlas account
  - name: macosx-10.10
    driver:
      box: chef/macosx-10.10 # private box in Chef's Atlas account
      provider: vmware_fusion
      require_chef_omnibus: '12.2.0'
  - name: macosx-10.11
    driver:
      box: chef/macosx-10.11 # private box in Chef's Atlas account
      provider: vmware_fusion
      require_chef_omnibus: '12.2.0'
  - name: sles-12-sp1
    driver:
      box: chef/sles-12-sp1-x86_64 # private box in Chef's Atlas account

suites:
- name: default
  run_list:
  - recipe[test::default]
- name: upgrade
  run_list:
  - recipe[test::version_upgrade]
